import logoDetailProduct from '../assets/product/product2.png'

export const cartData = [
    {
        id: 1,
        quantity: 2,
        user_id: 101,
        id_store: 1,
        product_id: 201,
        product_name: "Áo Thun",
        name_store: "Cửa Hàng Thời Trang",
        logo_product: logoDetailProduct,
        discount: 10,
        price_sale: 180000,
        price: 200000,
        stock: 50,
        attribute1: "Màu Trắng",
        attribute2: "Size M",
    },
    {
        id: 2,
        quantity: 1,
        user_id: 102,
        id_store: 2,
        product_id: 202,
        product_name: "Quần Jean",
        name_store: "Thời Trang Nam",
        logo_product: logoDetailProduct,
        discount: 15,
        price_sale: 340000,
        price: 400000,
        stock: 30,
        attribute1: "Màu Xanh",
        attribute2: "Size 32",
    },
    {
        id: 3,
        quantity: 3,
        user_id: 101,
        id_store: 1,
        product_id: 203,
        product_name: "Giày Thể Thao",
        name_store: "Sport Shop",
        logo_product: logoDetailProduct,
        discount: 20,
        price_sale: 800000,
        price: 1000000,
        stock: 20,
        attribute1: "Màu Đen",
        attribute2: "Size 42",
    },
    {
        id: 4,
        quantity: 1,
        user_id: 103,
        id_store: 3,
        product_id: 204,
        product_name: "Balo",
        name_store: "Phụ Kiện Thời Trang",
        logo_product: logoDetailProduct,
        discount: 5,
        price_sale: 950000,
        price: 1000000,
        stock: 15,
        attribute1: "Màu Xám",
        attribute2: "Chống Nước",
    },
    {
        id: 5,
        quantity: 4,
        user_id: 104,
        id_store: 4,
        product_id: 205,
        product_name: "Mũ Lưỡi Trai",
        name_store: "Đồ Dùng Hàng Ngày",
        logo_product: logoDetailProduct,
        discount: 10,
        price_sale: 90000,
        price: 100000,
        stock: 100,
        attribute1: "Màu Đỏ",
        attribute2: "Chất Liệu Cotton",
    }
]